services:
  flask_api:
    build: ./packages/server
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      # Flask 3 prefers FLASK_DEBUG over FLASK_ENV
      - FLASK_APP=packages/server/app.py
      - FLASK_DEBUG=1
