services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NEXT_TELEMETRY_DISABLED=1
  flask_api:
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      # Flask 3 prefers FLASK_DEBUG over FLASK_ENV
      - FLASK_APP=server/app.py
      - FLASK_DEBUG=1
